# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csingi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterstory',
            name='character_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csingi.Players'),
        ),
        migrations.AlterField(
            model_name='players',
            name='character_name',
            field=models.CharField(max_length=25),
        ),
    ]
